apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "$APP_NAME"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "$APP_NAME"
    spec:
      containers:
        - name: "$APP_NAME"
          image: "$REGISTRY_URL/$IMAGE_NAME"
          ports:
          - containerPort: 8080