apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: bugbash1621
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bugbash1621
    spec:
      containers:
        - name: bugbash1621
          image: kapasrijkubacr.azurecr.io/bugbash162-1a0ec
          ports:
          - containerPort: 8080