env:
  REGISTRY_URL: kapasrijkubacr.azurecr.io
  SERVICE_NAME: kpjavakubernetes
  NAMESPACE: kpjavakubernetes
  IMAGE_NAME: kpjavakubernetes
  APP_NAME: kpjavakubernetes
  SECRET_NAME: kpjavakubernetesdockerauth
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "$APP_NAME"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "$APP_NAME"
    spec:
      containers:
        - name: "$APP_NAME"
          image: "$REGISTRY_URL/$IMAGE_NAME"
          ports:
          - containerPort: 8080
