apiVersion: v1
kind: Service
metadata:
    name: bugbash1621-a0a5
    labels:
        app: bugbash1621-a0a5
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: bugbash1621-a0a5
