apiVersion: v1
kind: Service
metadata:
    name: "$APP_NAME"
    labels:
        app: "$APP_NAME"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "$APP_NAME"