apiVersion: v1
kind: Service
metadata:
    name: ${{ env.APP_NAME }}
    labels:
        app: ${{ env.APP_NAME }}
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: ${{ env.APP_NAME }}
